package tta.astrologerapp.talktoastro.volley;

/**
 * Created by Sonia Gupta on 3/8/2019.
 */
public enum RequestIdentifier {
    LOGIN,
    STATUS,
    CHATSTATUS,
    CALLHISTORY,
    CHATHISTORY,
    ARTICLES,
    EDITUSERPROFILE,
    USERPROFILE,
    DEVICTOKEN,
    UPDATEUSERWALLET,
    ASTROCALLPARAMETER,
    GETASTROSTATUS,
    GETASTROCHATSTATUS,
    PRIVACYPOLICY,
    RTMTOKEN,
    CHATFCMNOTIFICATION,
    VIEWCHAT,
    SAVECHAT,
    ENDCHAT,
    APPNOTIFICATION,
    ASKFREEQUESTION,
    HUBANSWER,
    HUBANSWERSUBMIT,
    HUBQUESTIONSUBMIT,
    ASTROLOGER_LIST,
    ASTROPROFILE,
    REPORTHISTORY,
    REPORTDETAIL,
    REPORTREQUIREMENT,
    REPORTCOMMENTSUBMIT,
    VERIFYOTP,
    GETAPPVERSION,
    CHATJOINSTATUS
}
